hadolint/language-docker

- .travis.yml
- Makefile
- integration-tests/.gitignore
- integration-tests/parseFile.hs
- integration-tests/parse_files.sh
I have added a modified script (from hadolint) that downloads real world `Dockerfile`s and then tries to parse them using `parseFile` from `Language.Docker`. I would add it as Travis test but it is failing to parse a few of them. Please try it using
```
make tests
```
> Add integration test for parsing real-world Dockerfiles

- examples/complex.hs
- src/Language/Docker/Normalize.hs
- test/Language/Docker/ParserSpec.hs
Re-implemented the normalizer to remove comment lines inside other instructions.
This solves cases like https://github.com/hadolint/hadolint/issues/76
> Remove inline comments

- src/Language/Docker/EDSL/Quasi.hs
- src/Language/Docker/Lexer.hs
- src/Language/Docker/Parser.hs
- src/Language/Docker/PrettyPrint.hs
- src/Language/Docker/Syntax.hs
- test/Language/Docker/ParserSpec.hs
The broken case was found in one of the failing integration tests.
This required a full re-implementation of the Lexer. I decided to drop
the makeTokenParser since it has been a struggle form the start to manage
the way it munges whitespace.
Instead, implemented the token parsers in the lexer by hand, since we only
needed a few of them.
> Fix another case of ENV parsing

- examples/complex.hs
- integration-tests/parse_files.sh
- src/Language/Docker/Normalize.hs
When a line ends with \ and the next one is empty, that's still valid
> Fixed another normalization case

- src/Language/Docker/Lexer.hs
- src/Language/Docker/Parser.hs
- test/Language/Docker/ParserSpec.hs
It seems like LABEL and ENV uses the same parsing lines in docker build,
so let's do the same. Also, labels allow quoted keys, and ENV does as well
> Fixed the LABEL parser

- src/Language/Docker/EDSL.hs
- src/Language/Docker/Parser.hs
- src/Language/Docker/PrettyPrint.hs
- src/Language/Docker/Syntax.hs
- test/Language/Docker/EDSLSpec.hs
- test/Language/Docker/ParserSpec.hs
It looks like it is also possible to do this:
`EXPOSE 80 81 8080-8085`
Unfortunatey, this required another change in the Syntax model
> Fixed EXPOSE parsing for ranges

- .travis.yml
- README.md
- examples/templating.hs
- examples/test-dockerfile.hs
- language-docker.cabal
- package.yaml
- src/Language/Docker.hs
- src/Language/Docker/EDSL.hs
- src/Language/Docker/EDSL/Types.hs
- src/Language/Docker/Lexer.hs
- src/Language/Docker/Parser.hs
- src/Language/Docker/Predef.hs
- src/Language/Docker/PrettyPrint.hs
- src/Language/Docker/Syntax.hs
- src/Language/Docker/Syntax/Lift.hs
- stack.yaml
- test/Language/Docker/EDSLSpec.hs
- test/Language/Docker/ParserSpec.hs
* Better Syntax representation for COPY and ADD
* Support for parsing copy and add flags (`--chown` and `--from`)
Additionally, bumped the `lts` requirement to `lts-10.0` since I really like the error messages and the new compiler speed
> Improve COPY and ADD parsing

- README.md
- src/Language/Docker.hs
- src/Language/Docker/EDSL.hs
- src/Language/Docker/Parser.hs
- src/Language/Docker/PrettyPrint.hs
- src/Language/Docker/Syntax.hs
- src/Language/Docker/Syntax/Lift.hs
- test/Language/Docker/EDSL/QuasiSpec.hs
- test/Language/Docker/EDSLSpec.hs
- test/Language/Docker/ParserSpec.hs
This is a breaking change, but improves the usability of copy and entrypoint
functions. Also adds the possibility to specify a from stage and permissions
for the copy argument
closes #21 and #22
> Improved the edsl for copy and entrypoint

- integration-tests/parseFile.hs
- package.yaml
- src/Language/Docker.hs
- src/Language/Docker/EDSL.hs
- src/Language/Docker/EDSL/Quasi.hs
- src/Language/Docker/EDSL/Types.hs
- src/Language/Docker/Parser.hs
- src/Language/Docker/PrettyPrint.hs
- src/Language/Docker/Syntax.hs
- stack.yaml
- test/Language/Docker/EDSL/QuasiSpec.hs
- test/Language/Docker/EDSLSpec.hs
- test/Language/Docker/ParserSpec.hs
Megaparsec 7 is also faster, but forces a change in the API we expose, so have to bump our version to 8
> Using megaparsec 7, wich outputs prettier errors

- package.yaml
- src/Language/Docker/Parser.hs
- test/Language/Docker/ParserSpec.hs
It failed before when there were spaces before the comma
> Correctly parsing comma separated lists

- test/Language/Docker/ParserSpec.hs
Ran into an issue with ENV vars and reported it at https://github.com/hadolint/hadolint/issues/428 then dived into why this was happening and found that the actual parsing is done here.
Todo:
> Add support for escaped quoting

- language-docker.cabal
- package.yaml
- src/Language/Docker/Parser/Run.hs
- src/Language/Docker/PrettyPrint.hs
- src/Language/Docker/Syntax.hs
- test/Language/Docker/ParserSpec.hs
- test/fixtures/2.Dockerfile
I had misunderstood that the sharing argument was required, but it is
not.
> Fixed parsing of --mount=type=cache

- src/Language/Docker/Parser/Instruction.hs
- test/Language/Docker/ParserSpec.hs
Improve the parser by correctly handling `ARG` instructions that do not
have a default, but do have a `=`. E.g.:
```
ARG FOO=
```
Previously, the parser would consume all characters until EOL as
argument name in this case, which is wrong, since the `=` sign should
not be part of the argument name in this case.
Fixes https://github.com/hadolint/hadolint/issues/510
> parser: Handle `ARG` instructions without default

- src/Language/Docker/Parser/Run.hs
- test/Language/Docker/ParserSpec.hs
- Remove unused compiler pragma
- Add capability to deal with explicit boolean values for experimental
mount option `required` to parser
The experimental option `--mount=type=[secrec|ssh],...` may have the
prarmeter `required` either with a boolean value, or alone:
```Dockerfile
RUN --mount=type=secret,required
RUN --mount=type=secret,required=[true|false]
```
fixes: https://github.com/hadolint/hadolint/issues/444
BTW: Releases and possibly code on Github are a few versions behind [Hackage](https://hackage.haskell.org/package/language-docker)
> parser: fix experimental option `required`

- language-docker.cabal
- src/Language/Docker/Parser/Copy.hs
- src/Language/Docker/PrettyPrint.hs
- src/Language/Docker/Syntax.hs
- test/Language/Docker/ParserSpec.hs
- test/Language/Docker/PrettyPrintSpec.hs
- add support for the --chmod flag for `ADD`
- add support for the --chmod flag for `COPY`
- add tests for the --chmod flag
Buildkit supports setting a new mode on a file during `COPY`/`ADD`
instructions with the --chmod flag. See: https://github.com/moby/buildkit/pull/1492
fixes: https://github.com/hadolint/hadolint/issues/609
> syntax: add support for --chmod flags   #609

- language-docker.cabal
- package.yaml
- src/Language/Docker/Parser.hs
- src/Language/Docker/Parser/Arguments.hs
- src/Language/Docker/Parser/Cmd.hs
- src/Language/Docker/Parser/Copy.hs
- src/Language/Docker/Parser/Expose.hs
- src/Language/Docker/Parser/From.hs
- src/Language/Docker/Parser/Healthcheck.hs
- src/Language/Docker/Parser/Instruction.hs
- src/Language/Docker/Parser/Pairs.hs
- src/Language/Docker/Parser/Prelude.hs
- src/Language/Docker/Parser/Run.hs
- src/Language/Docker/PrettyPrint.hs
- src/Language/Docker/Syntax.hs
- test/Language/Docker/IntegrationSpec.hs
- test/Language/Docker/ParsePragmaSpec.hs
- test/Language/Docker/ParserSpec.hs
- test/Language/Docker/PrettyPrintSpec.hs
- test/TestHelper.hs
- test/fixtures/3.Dockerfile
- test/fixtures/4.Dockerfile
- test/fixtures/5.Dockerfile
- test/fixtures/6.Dockerfile
- test/fixtures/7.Dockerfile
- test/fixtures/8.Dockerfile
- Add handling for parser directives (pragmas) to the parser:
`escape`, `index`
- Split off tests into separate modules
- Version bump to 9.4.0
See also:
https://docs.docker.com/engine/reference/builder/#parser-directives
fixes: https://github.com/hadolint/hadolint/issues/371
fixes: https://github.com/hadolint/language-docker/issues/48
> parser: handle parser directives

- language-docker.cabal
- package.yaml
List all Dockerfiles for tests in `package.yaml` and
`language-docker.cabal`.
- fixes: https://github.com/hadolint/language-docker/issues/63
> stack: add Dockerfiles to `package.yaml`

- language-docker.cabal
- package.yaml
- src/Language/Docker/Parser/Expose.hs
- test/Language/Docker/ParserSpec.hs
- test/TestHelper.hs
Propagate the correct error message `invalid protocol` upwards in case
parsing an expose expression fails because a wrong protocol was
specified.
fixes: https://github.com/hadolint/hadolint/issues/675
> feature: report invalid protocol

- .github/workflows/haskell.yml
- .github/workflows/hlint.yml
- Add linting workflow utilizing `hlint`
- Add unit test workflow utilizing `cabal test`
Given how annoying even a small bug would be in this library, as it would result in a whole lot of version bumping, we should at least run the unit tests we have here against any new code to ensure no breakage happens. Ideally we would build and run Hadolints unit tests as well against any new code, but that would take some more effort to accomplish.
These unit tests are lifted straight from hadolint/hadolint.
> workflow: Add linting and unit testing

- language-docker.cabal
- package.yaml
- src/Language/Docker/Parser/Prelude.hs
- test/Language/Docker/ParseCopySpec.hs
- test/Language/Docker/ParseRunSpec.hs
Fix parsing error on line continuation.
The `Text.Megaparsec.Lexer.charLiteral` parser will not parse just any
Char, but will instead make exceptions for escaped characters and
quotes. This resulted in a faulty behaviour when encountering a literal
backslash `\` in a heredoc right before a newline.
The `Text.Megaparsec.anySingle` parsed will instead not make exceptions
for escaped characters and therefore parse the content of a heredoc just
as it is in the input, which is the desired behaviour.
Additionally a test case for the `ADD` and `COPY` instruction has been
added to make sure the parser continues to accept this kind of input.
fixes: https://github.com/hadolint/hadolint/issues/699
> heredocs: fix parsing bug with line continuations

- language-docker.cabal
- package.yaml
- src/Language/Docker/Parser/Prelude.hs
- test/Language/Docker/ParseRunSpec.hs
- Simplyfy heredoc marker detection by replacing the use of
`L.charLiteral` with `anySingle` and replace a custom whitespace
parser with the unicode compatible `spaceChar` parser.
- Fix heredoc termination in cases where the a string equal to the
termination marker is observed within the heredoc itself in a position
where is clearly is not meant to terminate the heredoc.
Heredocs are terminated by the termination marker __on its own line__.
> bugfix: heredoc termination, unicode whitespaces

- src/Language/Docker/Parser/Run.hs
- src/Language/Docker/Syntax.hs
- test/Language/Docker/ParseRunSpec.hs
Parser the uid/gid options in the `--mount` option to the `RUN`
instruction as string. This allows the arguments to those options to be
variables (e.g. build arguments):
```
RUN --mount=type=cache,target=/foo,uid=$UID,gid=$GID echo foo
```
fixes: https://github.com/hadolint/hadolint/issues/705
This is a breaking API change.
> parser: parser uid/gid in `RUN --mount` as string

- src/Language/Docker/Parser/Prelude.hs
- test/Language/Docker/ParseRunSpec.hs
Even though POSIX clearly states that the delimiter should be on its
own line, followed by a newline, the parser should also accept when a
document just ends after the delimiter.
fixes: https://github.com/hadolint/hadolint/issues/736
> bugfix: handle heredocs followed by EOF

- src/Language/Docker/Parser/Prelude.hs
- src/Language/Docker/Parser/Run.hs
- test/Language/Docker/ParseRunSpec.hs
Allow explicitly setting `ro=true` and similarly for `rw` and `false`
and all permutations thereof in the buildkit `--mount` arguments for
bind- and cache mounts.
fixes: https://github.com/hadolint/hadolint/issues/738
> parser: Allow buildkit --mount arguments ro/rw be explicit

- src/Language/Docker/Parser/Prelude.hs
- test/Language/Docker/ParseRunSpec.hs
- Fix overzealous parsing of a `RUN` instruction in case later on a
heredoc follows
A `RUN` instuctions heredoc syntax supports passing the heredoc content
to stdin of a command by writing e.g.
```Dockerfile
RUN command <<EOF
this is a heredoc
EOF
```
In order to parse this command, tokens must be consumed until a heredoc
is encountered. However we must stop and fail the heredoc parser if
before a heredoc marker is encoutered a newline is encountered, because
otherwise this example will mistakenly consume instructions as commands
in the `RUN` instruction:
```Dockerfile
RUN foo bar
FROM newstage  # this instruction would be parsed as if it were a line
COPY <<EOF /destination.sh
this is a heredoc
EOF
```
fixes: https://github.com/hadolint/hadolint/issues/761
> heredoc parsing: fix overzealous parsing

- language-docker.cabal
- src/Language/Docker/Parser/Arguments.hs
- src/Language/Docker/Parser/Copy.hs
- src/Language/Docker/Parser/Prelude.hs
- src/Language/Docker/Parser/Run.hs
- test/Language/Docker/ParseCmdSpec.hs
- test/Language/Docker/ParserSpec.hs
- Fix parsing of long strings broken into multiple lines in the
exec/JSON format of CMD, RUN and ENTRYPOINT statements
- Remove legacy alias `stringLiteral` from
Language.Docker.Parser.Prelude
When specifying a command with arguments in JSON notation (aka. exec
format), sometimes it is useful to break a longer string into several
lines. Although this is not legal JSON syntax, it is supported by Docker
and results are as expected. Therefore the parser should not fail on
these occasions, but rather produce the expected result. In addition to
that the parser needs to remove escaped newlines from the resulting
string.
The legacy alias `stringLiteral` from the Language.Docker.Parser.Prelude
module has been removed, because now there is a difference between
parsing a double quoted string …
> parser: fix parsing broken strings in exec format

- language-docker.cabal
- package.yaml
- src/Language/Docker/Parser/Expose.hs
- src/Language/Docker/PrettyPrint.hs
- src/Language/Docker/Syntax.hs
- src/Language/Docker/Syntax/Port.hs
- src/Language/Docker/Syntax/PortRange.hs
- src/Language/Docker/Syntax/Protocol.hs
- test/Language/Docker/ParseExposeSpec.hs
- test/Language/Docker/ParserSpec.hs
- Fix parser being unable to parse port ranges when the limits are expressed with variables
- Rearrange AST such that the limits of port ranges are ports
- Move tests for `EXPOSE` instructions to their own file
This change introduces a breaking change to the AST.
The old AST was unable to represent port ranges delimited with variables, since the data type for port ranges mandated that a limit must be expressed as an integer. This creates problems when limits of a range are expressed as variables (e.g. as ARGs). The change to the AST defines the limits of a port range as port. This has the advantage that any way a port can be expressed can also be used to express a port range limit, including variables.
required-for: https://github.com/hadolint/hadolint/issues/876
Since this would be a …
> ast/parser: vairables in port ranges

- src/Language/Docker/Parser/Arguments.hs
- src/Language/Docker/Parser/Prelude.hs
- test/Language/Docker/ParseRunSpec.hs
Fix parsing error with heredocs within command chains with escaped newlines.
When chaining commands in a `RUN` instructions, it is possible that one of the middle commands takes a heredoc. It is often convenient to also break up the resulting long line with escapes, e.g.:
```Dockerfile
RUN foo \
&& bar <<EOF >> bar.txt \
&& baz
inside heredoc
content
EOF
```
The heredoc parser should not fail on escaped newlines in this command chain.
This requires two modifications:
- Parsing the rest of the command chain, after a heredoc should not end on the literal '\n' character, but should be done with the `untilEol` parser, which respects the escaped newlins
- Parsing the command chain before the heredoc requires casting escaped newlines to spaces as to not fail the parser on a '\n' character
This …
> fix: heredocs in lines with escaped newlines

- language-docker.cabal
- src/Language/Docker/Parser/Healthcheck.hs
- src/Language/Docker/Parser/Prelude.hs
- src/Language/Docker/Syntax.hs
- test/Language/Docker/ParseHealthcheckSpec.hs
- test/Language/Docker/ParserSpec.hs
Parse fractional numbers as arguments to flags for the `HEALTHCHECK` instruction.
The `HEALTHCHECK` instruction can take an `--interval`, `--timeout` or `--start-period` flag specifying details to the healthcheck repetition behaviour. This can also be specified with fractions (of secods, minutes or hours), e.g.:
```Dockerfile
HEALTHCHECK \
--interval=0.5s \
CMD curl -f http://localhost
```
With the caveat that somewhere from parsing to conversion to a DiffTime some precision is lost (DiffTime has a precision of 10^-12s), this change adds support for the arguments to these interval flags to be specified as fractional numbers.
fixes: https://github.com/hadolint/hadolint/issues/893
Signed-off-by: Moritz Röhrich <moritz@ildefons.de>
> fix: parse fractional arguments to flags

- src/Language/Docker/Syntax/PortRange.hs
Pretty print `PortRange` at  ad383b6bcf426930886978bd80ca0e2da5d6028c
```
>> prettyPrintPortSpec $ PortRangeSpec $ PortRange (Port 8080 TCP) (Port 8085 TCP)
8080-8085
>> prettyPrintPortSpec $ PortRangeSpec $ PortRange (Port 8080 TCP) (Port 8085 UDP)
8080-8085/udp
>> prettyPrintPortSpec $ PortRangeSpec $ PortRange (Port 8080 UDP) (Port 8085 TCP)
8080-8085/udp
>> prettyPrintPortSpec $ PortRangeSpec $ PortRange (Port 8080 UDP) (Port 8085 UDP)
8080-8085/udp/udp
```
I think that `PortRange (Port 8080 UDP) (Port 8085 UDP)` is expected pretty print to `8080-8085/udp`.
So fix it.
And removed `(PortRange (PortStr start) (Port end UDP))` case because this case is contained `(PortRange start end)` case.
> fix: pretty port range with udp and udp

- integration-tests/parse_files.sh
- language-docker.cabal
- package.yaml
- src/Language/Docker/Parser/Copy.hs
- src/Language/Docker/PrettyPrint.hs
- src/Language/Docker/Syntax.hs
- test/Language/Docker/ParseAddSpec.hs
- test/Language/Docker/PrettyPrintSpec.hs
This PR adds support for the `--checksum` flag in the `ADD` instruction:
https://docs.docker.com/engine/reference/builder/#verifying-a-remote-file-checksum-add---checksumchecksum-http-src-dest
Note, I know nothing about the Haskell programming language - I have written this by looking at this other PR https://github.com/hadolint/language-docker/pull/84. So please be kind!
Final goal would be to add another rule to Hadolint recommending the use of `ADD --checksum` with remote sources.
> Add 'ADD --checksum' support

- src/Language/Docker.hs
~~~
src/Language/Docker.hs:26:5: error: [GHC-97219]
Duplicate record field ‘sourcePaths’ in export list:
‘Language.Docker.Syntax.AddArgs(..)’ exports the field ‘Language.Docker.Syntax.sourcePaths’
belonging to the constructor ‘Language.Docker.Syntax.AddArgs’
imported qualified from ‘Language.Docker.Syntax’ at src/Language/Docker.hs:46:1-39
(and originally defined at src/Language/Docker/Syntax.hs:193:9-19)
‘Language.Docker.Syntax.CopyArgs(..)’ exports the field ‘Language.Docker.Syntax.sourcePaths’
belonging to the constructor ‘Language.Docker.Syntax.CopyArgs’
imported qualified from ‘Language.Docker.Syntax’ at src/Language/Docker.hs:46:1-39
(and originally defined at src/Language/Docker/Syntax.hs:174:9-19)
~~~
Fixes https://github.com/hadolint/language-docker/issues/93.
> Language.Docker: enable DuplicateRecordFields to fix build error with ghc-9.8.x

- src/Language/Docker/Parser/Copy.hs
- src/Language/Docker/PrettyPrint.hs
- src/Language/Docker/Syntax.hs
- test/Language/Docker/ParseAddSpec.hs
- test/Language/Docker/ParseCopySpec.hs
- test/Language/Docker/PrettyPrintSpec.hs
Hello,
See https://github.com/hadolint/hadolint/issues/1029, https://github.com/hadolint/language-docker/issues/96.
I have absolutely no knowledge about Haskell, so please bear with me 😇 .
Since [Dockerfile 1.7,](https://www.docker.com/blog/new-dockerfile-capabilities-v1-7-0/) the new `--exclude` flag has been added to the `ADD` and `COPY` command. This PR attempts to add the support for this new flag.
Feel free to adapt the PR according to the project standard. I didn't run any test locally, yet.
If this PR is welcomed, I'll add the support for the `--parents` flag as well, in another PR.
Thanks!
> Add support for the --exclude flag
